### ISSUE TITLE
Observing list: object name isn't used sometimes

### ISSUE THREAD

**Issue by markusd112** [Stellarium/stellarium#2309]
### Expected Behaviour
A selected object should be add to the observing list with its name

### Actual Behaviour
When selecting an object in Stellarium (e.g. sh2-246) and adding it to an observing list, it is displayed in the editing dialogue, but the object name is not "sh2-246", but the coordinates of the object. When I press "save & close", the new object isn't add to the observing list.
sh2-246 has been selected in stellarium and add to the observing list:
![Screenshot 2022-02-28 142528](https://user-images.githubusercontent.com/14372683/155990986-59da2325-8952-40af-a477-31c0f1439100.png)

When pressing "Save & Close" the new entry isn't add to the list:
![Screenshot 2022-02-28 142551](https://user-images.githubusercontent.com/14372683/155990984-4e66e80c-d35b-4b86-b111-08819ad9db83.png)

### Steps to reproduce
- CTRL+F to find "sh2-246"
- ALT-B to open observing list
- edit the list
- add the selected sh2-246
- button "save & close"

--> sh2-246 isn't add to the list.

### System
* Stellarium version: 0.21.3
* Operating system: Windows 10

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/8153638/log.txt)

**Comment by Jocelyn1109** [comment]
Hi @markusd112  and thank your for the message. 
It is very strange but I will fix the problem.

Jocelyn

**Comment by LucaAmerio** [comment]
Note, I'm running v 0.22.1

**Comment by Jocelyn1109** [comment]
@LucaAmerio 
"when you speak at the past, do you mean that this is already in a release" -> yes this is already in the current version of Stellarium but the problem is fixed in the ObservingLIST V2.

"Can you add the possibility to manually change the name?" -> no it's not planned at the moment and I don't think it concerns the ObservingList. It's app-wide.

Jocelyn

**Comment by LucaAmerio** [comment]
Sorry @Jocelyn1109 , maybe it's just me not understanding. 
I downloaded the latest version few hours ago and I can confirm the in the Observing List in this release (i think this is still V1) the bug is still present: objects that don't display the green DSO square cannot be added to the observing list. They appear as RA/DEC when editing the list, and they disappear when you do "Save and Close".

Is there a way to use the ObservingListV2 in Stellarium 0.22.1 ?
