### ISSUE TITLE
New DSO marker colour problems

### ISSUE THREAD

**Issue by Menno5** [Stellarium/stellarium#3302]
### Expected Behaviour
Clear distinctive color differences in default DSO marker colours like in V 23.1.

### Actual Behaviour
Washed out, harder to see difference in default DSO marker colours in V 23.2.

In the DSO colour settings of V 23.2, the colour of galaxies is set to the same Red as in V 23.1. But onscreen in V 23.2 this is now a kind of soft red with what looks like a white overlay or background line.
The same goes for example for the blue of interacting galaxies: in V 23.1 a distinctive blue, in V 23.2 a washed out blue that is very hard to see. Setting this to "hard blue" gives a kind of purple colour.
So it's very hard to set colours in V 23.2 because the colour settings do not result in the same colours onscreen for the DSO markers.

See screenshot.
On top are the default colours of DSO markers of a clean install of V 23.1.
Below that the default colours of DSO markers of a clean install of V 23.2.

### System
* Stellarium version: stellarium-23.2-qt6-win64.exe
* Operating system: Windows 11, latest up to date version
* Graphics Card: MSI RTX 2080 TI Gaming X Trio / NVidia driver, version 536.40

![marker-colors](https://github.com/Stellarium/stellarium/assets/56191878/4b4bc9c2-4995-4c6b-b58b-8717473d81ff)

**Comment by alex-w** [comment]
Please check color settings for DSO markers - you should have something like this:
![stellarium-008](https://github.com/Stellarium/stellarium/assets/88731/a5afd9a9-bea7-439f-9ffa-74ada9fe08fd)

**Comment by 10110111** [comment]
I don't reproduce. The second screenshot looks as if the red markers are duplicated with white color.

**Comment by gzotti** [comment]
Yes, I also see that. But how can this happen? Any driver settings you can think of?

**Comment by alex-w** [comment]
> Yes, I also see that. But how can this happen? Any driver settings you can think of?

I can't see the issue on macOS. Would you share DSO color settings?

**Comment by Menno5** [comment]
Did some more testing.
For the screenshot below, I changed the color for galaxies to a reddish color. This gives white DSO galaxy markers while in the settings it's clearly reddish.
I did also test the color settings of the Markings and gave the Equatorial Grid the same color as the DSO galaxy color (#fe3333) and the grid is showing just fine in red like in V 23.1 there where galaxies with #fe3333 are showing the washed out red.
So it seems to be isolated to the DSO Marker colours.

![color1](https://github.com/Stellarium/stellarium/assets/56191878/3e1c9916-6a28-42fc-8bb1-2e4376dcc031)

**Comment by 10110111** [comment]
> tried a fresh install

Does "fresh install" mean that you wipe your settings on uninstalling, so the subsequent install is clean?

> So it seems to be isolated to the DSO Marker colours.

Could you uncheck all irrelevant items in the View/DSO dialog, and filter out by type irrelevant objects? I still suspect that somehow you have duplicated data somewhere, maybe turning off some of these items would make it clearer which ones look white.

Also, please attach Stellarium log file.

**Comment by Menno5** [comment]
> Does "fresh install" mean that you wipe your settings on uninstalling, so the subsequent install is clean?

Yes, wiped all. I only made a backup (saved in different location) of my Observing List but did not import that yet.

> Could you uncheck all irrelevant items in the View/DSO dialog, and filter out by type irrelevant objects? I still suspect that somehow you have duplicated data somewhere, maybe turning off some of these items would make it clearer which ones look white.

I unchecked all and then only checked PGC. These are then in the washed out red and yellow colours.
Checked IC only and here too washed colours. But only for the oval indicators, the symbols for a planetary nebula and the Ha Regions though, are in normal bright green colour?

Attached the log file.
[log.txt](https://github.com/Stellarium/stellarium/files/11951455/log.txt)

**Comment by Menno5** [comment]
Just in case, here also a log with OpenGL diagnostics.

[OpenGL-log.txt](https://github.com/Stellarium/stellarium/files/11952022/OpenGL-log.txt)

**Comment by alex-w** [comment]
@10110111 any news?

**Comment by 10110111** [comment]
Until I can reproduce it, there won't be any news. Currently I can't.

**Comment by 10110111** [comment]
What do you mean by partially?

**Comment by alex-w** [comment]
> What do you mean by partially?

See marker and color for active galaxy for example

![stellarium-046](https://github.com/Stellarium/stellarium/assets/88731/ab4b2393-6448-432d-ae17-76c71781f89c)

**Comment by 10110111** [comment]
From your JPEG I can't tell the exact color due to color ringing artifacts. Screenshots should use lossless compression to be most useful, e.g. PNG.

**Comment by alex-w** [comment]
![stellarium-007](https://github.com/Stellarium/stellarium/assets/88731/f071da55-da41-4756-95a9-c7db2ec52969)

**Comment by 10110111** [comment]
So, the object you chose is `#ff8033`, which is the default color of active galaxies. The buttons as rendered in this GUI are quite misleading regarding the color they represent, so I can't match them with the actual marker. But if you didn't change the setting, the render seems correct. You can check in the actual color picker and compare with what PixelTool or other screen magnifier tells you.

**Comment by gzotti** [comment]
Is the slight color mismatch between color button and galaxy marker due to your translation of the latter to a linear color space?
Else this screen looks OK. The white galaxies are odd but we have no further information.

**Comment by 10110111** [comment]
> Is the slight color mismatch between color button and galaxy marker due to your translation of the latter to a linear color space?

Nothing is being translated to linear color space, we haven't merged any related change. The buttons are just rendered as tinted gradients instead of the exact flat colors that they should have. It's a UX problem that should be fixed, but it's unrelated to the current marker issue.

**Comment by 10110111** [comment]
Why? What exactly is the issue? In the screenshot everything looks OK.

**Comment by gzotti** [comment]
Maybe there are tweaks to how the color button can be rendered. Something without pseudo-3D effect or gradient. But this is indeed a different (and purely cosmetic) issue from this one.

**Comment by Menno5** [comment]
> Why? What exactly is the issue? In the screenshot everything looks OK.

HI
The issue is still the same as my 2 screenshots with the first posting on top of this page. Those are PNG images.
With _exactly_ the same pallets, most of the colors of DSO's in 23.2 are washed out in comparison to  23.1.

**Comment by 10110111** [comment]
> The issue is still the same as my 2 screenshots with the first posting on top of this page.

Yes, the problem is that no one of the developers can reproduce it on their machines to be able to debug.

**Comment by Menno5** [comment]
If there is anything I can do other then the earlier provided log, just let me know? I'm no coder whatsoever but I can work with instructions.
For now I did just adjust the colors in the settings, so it looks fine. The only weird thing indeed is that the color in the settings/pallet looks different then the DSO colors showed.

**Comment by alex-w** [comment]
Hello @Menno5!

Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by Menno5** [comment]
Hi Alex

Installed and all set to default settings.
The colors are washed out. The blue marker of an Interacting Galaxy for example is not clear if it's light blue or light green. 
There is a difference now though when checking and un-checking the _Labels and Markers_ checkbox: only the labels are now fading out or in. The colors of the markers are switched on or off,

Did check again if any other colors are effected as well but that's still not the case: grid lines, celestial sphere, cardinal points, etc. are the colors they are suppose to be, not washed out.
This is still the best way to check the difference: set for example the Meridian line to color #fe3333 (the default color for Galaxies) and the difference is there.

**Comment by alex-w** [comment]
Please show screenshots

**Comment by 10110111** [comment]
OK I've been able to reproduce this, but apparently, it only happens on NVIDIA GPUs with multisampling disabled. Doesn't happen on Intel UHD Graphics 620 regardless of multisampling setting, and doesn't happen on NVIDIA with multisampling enabled.

Also, if I enable _Proportional hints_ option, I can see an interesting structure in the enlarged ellipses: looks like the line segments that it's made of have pale-colored ends, while the bulk is correctly colored. See the screenshot below.

![Screenshot_2023-09-19_22-03-23](https://github.com/Stellarium/stellarium/assets/6376882/0dcf45fd-3614-41ee-9362-6c2e825ec44c)

**Comment by alex-w** [comment]
Smooth via shaders?

**Comment by 10110111** [comment]
> Smooth via shaders?

No, it's not feasible in principle, the result would be similarly bad as `GL_LINE_SMOOTH`, for the same reasons. Only multisampling works well (or supersampling, but this is much costlier and not needed here).

**Comment by Menno5** [comment]
Good to see there is an idea now :)
But here there is no difference when I enable or disable multisampling. At least, not in the Nvidia Control panel.

Another thing I noticed just now: when the option _Use outlines for big deep-sky objects_ is enabled, a bunch of galaxies are then suddenly the right red color. Looks to be random though: as soon as I move the FOV with my mouse, the red color jumps to another bunch of galaxies. When zooming in or out, also whole patches appear or disappear. See screenshots below.

![Clipboard02](https://github.com/Stellarium/stellarium/assets/56191878/cf790262-be94-4513-8cf4-450a386cb365)
![Clipboard03](https://github.com/Stellarium/stellarium/assets/56191878/cb75f9b7-ae25-4796-9e2c-a4a48a789e61)

**Comment by 10110111** [comment]
> But here there is no difference when I enable or disable multisampling. At least, not in the Nvidia Control panel.

NVIDIA Control Panel is not something expected by Stellarium. Whether multisampling is enabled in Stellarium's settings influences the logic to enable or disable legacy line smoothing. The setting is in `config.ini` under `video/multisampling`. Set it to the number of samples, say, 8 to properly enable.

**Comment by Menno5** [comment]
I see. Is it correct that multisampling isn't there by default? I had to add it manually and give it the 8 value.
After that, the colors are indeed as they should be.

**Comment by 10110111** [comment]
OK, my analysis appears to have been incomplete. The actual culprit is not the legacy rendering itself, since it would create only a minor ripple. The problem is that blending mode appears to be `src+dst` instead of the normal alpha blending `src*alpha+dst*(1-alpha)`. I suppose the source of this is the `sPainter.setBlending(true, GL_ONE, GL_ONE);` line inside `NebulaMgr::draw()`, which is never reset in this function, so this state propagates into the `DrawNebulaFuncObject` methods. This becomes obvious from the following screenshot, made with multisampling enabled:

![Screenshot_2023-09-20_01-10-34](https://github.com/Stellarium/stellarium/assets/6376882/801fb608-c37b-473b-8cf0-c4591114e1be)

Now, can anyone explain why this blending mode is needed there?

**Comment by 10110111** [comment]
> Is it correct that multisampling isn't there by default?

Yes, I wouldn't be surprised.

**Comment by Menno5** [comment]
Just in case, here my results.
Did a reset of all settings, including colors.
Added the line _multisampling = 8_ to config.ini under _video_.
All the markers are in correct colors now and the overall effect is clearer.
The option _Use outlines for big deep-sky objects_ is now also showing correctly, all markers stay the same colors.

**Comment by 10110111** [comment]
Apparently, the problematic part that sets blending mode is not in NebulaMgr. Still, I don't understand why that line there is needed. Anyway, below a patch that fixes this for me. If it doesn't break anything for you, I can push it. Needs to get into a new RC I think. 
```diff
diff --git a/src/core/modules/Nebula.cpp b/src/core/modules/Nebula.cpp
index 1611b15030..6397b5c138 100644
--- a/src/core/modules/Nebula.cpp
+++ b/src/core/modules/Nebula.cpp
@@ -750,6 +750,7 @@ void Nebula::renderDarkNebulaMarker(StelPainter& sPainter, const float x, const
     const float gap = 0.15*size;
     const float*const cossin = StelUtils::ComputeCosSinRhoZone((M_PIf/2)/(numPointsInArc-1),
                                    numPointsInArc-1, 0);
+    sPainter.setBlending(false);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(2*size/35, 1.f, 2.5f));
     sPainter.setColor(color, hintsBrightness);
@@ -861,6 +862,7 @@ void Nebula::renderMarkerRoundedRect(StelPainter& sPainter, const float x, const
         vertexData.push_back(bottomInnerY - roundRadius*sina);
     }
     const auto vertCount = vertexData.size() / 2;
+    sPainter.setBlending(false);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(2*size/35, 1.f, 2.5f));
     sPainter.setColor(color, hintsBrightness);
@@ -878,6 +880,7 @@ void Nebula::renderRoundMarker(StelPainter& sPainter, const float x, const float
     const auto scale = pixelRatio * StelApp::getInstance().getGlobalScalingRatio();
     size *= scale;
 
+    sPainter.setBlending(false);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(size/7, 1.f, 2.5f));
     sPainter.setColor(color, hintsBrightness);
@@ -921,6 +924,7 @@ void Nebula::renderEllipticMarker(StelPainter& sPainter, const float x, const fl
         vertexData.push_back(y + pointY*cosa + pointX*sina);
     }
     const auto vertCount = vertexData.size() / 2;
+    sPainter.setBlending(false);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(size/40, 1.f, 2.f));
     sPainter.setColor(color, hintsBrightness);
@@ -940,7 +944,7 @@ void Nebula::renderMarkerPointedCircle(StelPainter& sPainter, const float x, con
 
     texPointElement->bind();
     sPainter.setColor(color, hintsBrightness);
-    sPainter.setBlending(true, GL_ONE, GL_ONE);
+    sPainter.setBlending(false);
     const auto numPoints = StelUtils::getSmallerPowerOfTwo(std::clamp(int(0.4f*size), 8, 4096));
     const auto spriteSize = std::min(0.25f * 2*M_PIf*size / numPoints, 5.f);
     if(insideRect)
```

**Comment by gzotti** [comment]
What happens during toggling nebulae now? Is the blending smooth? 
I agree, the `sPainter.setBlending(true, GL_ONE, GL_ONE); ` looks strange. Would `sPainter.setBlending(true)` (with defaults GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA work?

**Comment by 10110111** [comment]
Yes, should work too. Didn't think of toggling animation.

**Comment by 10110111** [comment]
I'd also remove the call in NebulaMgr. So, the patch:
```diff
diff --git a/src/core/modules/Nebula.cpp b/src/core/modules/Nebula.cpp
index 1611b15030..661f14b1ef 100644
--- a/src/core/modules/Nebula.cpp
+++ b/src/core/modules/Nebula.cpp
@@ -750,6 +750,7 @@ void Nebula::renderDarkNebulaMarker(StelPainter& sPainter, const float x, const
     const float gap = 0.15*size;
     const float*const cossin = StelUtils::ComputeCosSinRhoZone((M_PIf/2)/(numPointsInArc-1),
                                    numPointsInArc-1, 0);
+    sPainter.setBlending(true);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(2*size/35, 1.f, 2.5f));
     sPainter.setColor(color, hintsBrightness);
@@ -861,6 +862,7 @@ void Nebula::renderMarkerRoundedRect(StelPainter& sPainter, const float x, const
         vertexData.push_back(bottomInnerY - roundRadius*sina);
     }
     const auto vertCount = vertexData.size() / 2;
+    sPainter.setBlending(true);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(2*size/35, 1.f, 2.5f));
     sPainter.setColor(color, hintsBrightness);
@@ -878,6 +880,7 @@ void Nebula::renderRoundMarker(StelPainter& sPainter, const float x, const float
     const auto scale = pixelRatio * StelApp::getInstance().getGlobalScalingRatio();
     size *= scale;
 
+    sPainter.setBlending(true);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(size/7, 1.f, 2.5f));
     sPainter.setColor(color, hintsBrightness);
@@ -921,6 +924,7 @@ void Nebula::renderEllipticMarker(StelPainter& sPainter, const float x, const fl
         vertexData.push_back(y + pointY*cosa + pointX*sina);
     }
     const auto vertCount = vertexData.size() / 2;
+    sPainter.setBlending(true);
     sPainter.setLineSmooth(true);
     sPainter.setLineWidth(scale * std::clamp(size/40, 1.f, 2.f));
     sPainter.setColor(color, hintsBrightness);
@@ -940,7 +944,7 @@ void Nebula::renderMarkerPointedCircle(StelPainter& sPainter, const float x, con
 
     texPointElement->bind();
     sPainter.setColor(color, hintsBrightness);
-    sPainter.setBlending(true, GL_ONE, GL_ONE);
+    sPainter.setBlending(true);
     const auto numPoints = StelUtils::getSmallerPowerOfTwo(std::clamp(int(0.4f*size), 8, 4096));
     const auto spriteSize = std::min(0.25f * 2*M_PIf*size / numPoints, 5.f);
     if(insideRect)
diff --git a/src/core/modules/NebulaMgr.cpp b/src/core/modules/NebulaMgr.cpp
index 508f7b1303..28eeab810c 100644
--- a/src/core/modules/NebulaMgr.cpp
+++ b/src/core/modules/NebulaMgr.cpp
@@ -698,8 +698,6 @@ void NebulaMgr::draw(StelCore* core)
 
     Nebula::hintsBrightness = hintsFader.getInterstate()*flagShow.getInterstate();
 
-    sPainter.setBlending(true, GL_ONE, GL_ONE);
-
     // Use a 4 degree margin (esp. for wide outlines)
     const float margin = 4.f*M_PI_180f*prj->getPixelPerRadAtCenter();
     const SphericalRegionP& p = prj->getViewportConvexPolygon(margin, margin);
```

**Comment by alex-w** [comment]
I fear the current properties for blending are existing by historical reasons :-/

P.S. No problem for make the RC4 tonight or tomorrow, but need fix in master

**Comment by alex-w** [comment]
@10110111 @gzotti any news?

**Comment by Menno5** [comment]
You all are the best! Working great!
