### ISSUE TITLE
skycultures anutan file mistake.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3838]
### Steps to reproduce

(install_dir)/skycultures/anutan/

No.1
description.en.utf8
line27 and line29 duplicate
"Te Rakau Tapu.........."

No.2
description.en.utf8
line15
"Group of four small starts...."

Perhaps it is not "starts" but "stars"?

No.3
No match. &alpha; and &beta; Cen
description.en.utf8
line26
"Te Rua Tangata"

star_names.fab
line18 and 21
"To Rua Tangata"

No.4
No match. &alpha; Sco
description.en.utf8
line28
"Te Kau"

star_names.fab
line16
"Na Kau"

No.5
No match. LMC
description.en.utf8
line31
"Te Aro Rere"

dso_names.fab
line6
"Te Ao Rere"

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
  + stellarium-24.2-98544be-patch-qt5-win32.exe
  + stellarium-24.2-623f996-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by gzotti** [comment]
Yes, I have seen some of these issues before. This is what we got from the authors. What we think looks like obvious typos may lie in the grammar of the original language. Nr.2 "stars" can be corrected by ourselves, OK. The rest must be clarified with the authors.

**Comment by alex-w** [comment]
Probably typos already fixed by @10110111

**Comment by 10110111** [comment]
What I fixed has already been released, so if this is in the latest release, I haven't fixed it.

**Comment by 3domennotry** [comment]
I also checked stellarium-24.2-623f996-qt5-win64.exe.
(I have both environments win7 32bit and win7 64bit.)

(install_dir)/skycultures/anutan/
These files are same to the environment I reported.
All are not fixed.

**Comment by alex-w** [comment]
Please use full package for testing sky cultures

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed in stellarium-24.2-19f4d98-qt5-win64.exe (full package).

(I have both environments win7 32bit and win7 64bit.
32bit win7 Full packages(stellarium-24.2-19f4d98-qt5-win32.exe) is not release.)

Thank you very much.
